# Generated by Django 4.1.4 on 2022-12-21 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_advertisement_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Ad',
        ),
    ]
