# Generated by Django 4.1.4 on 2022-12-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
